export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const UPDATE_ACCOUNT_ID = "UPDATE_ACOUNT_ID";
export const UPDATE_ACCOUNT_BILLS = "UPDATE_ACCOUNT_BILLS";
export const UPDATE_ACCOUNT_PAYS = "UPDATE_ACCOUNT_PAYS";
export const UPDATE_ACCOUNT_BUDGETS = "UPDATE_ACCOUNT_BUDGETS";
export const UPDATE_CHARGES = "UPDATE_CHARGES";